language: node_js
node_js:
    - "10"
env: ESLINT_VERSION=6.5.1
stages:
  - test
  - name: documentation
    if: branch = master
jobs:
  include:
    - stage: test
      script:
      - npm run typecheck
      - npm run lint
      - npm run test
      - npm run codecov
    - stage: documentation
      script:
        - npm run build
        - touch ./styleguide/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./styleguide
        target_branch: gh-pages
        on:
          branch: master
